package com.exception1;

public class TryFinally {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try
		{
			int a=10;
			System.out.println(a/0);
		}
		
		finally
		{
			System.out.println("Done...");
		}
		
		//catch - auto generated by JVM

	}

}
